# Generated by Django 3.2.7 on 2021-10-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.ManyToManyField(related_name='book_comments', to='comment.Comment'),
        ),
    ]
