# Generated by Django 3.2.7 on 2021-10-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        ('book', '0002_book_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='comments',
            field=models.ManyToManyField(null=True, related_name='book_comments', to='comment.Comment'),
        ),
    ]
