# Generated by Django 3.2.4 on 2021-11-05 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
