# Generated by Django 3.2.7 on 2021-11-27 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20211117_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='comments',
        ),
    ]
