# Generated by Django 3.2.4 on 2021-12-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_remove_book_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
