# Generated by Django 3.2.4 on 2021-11-30 00:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0008_remove_book_comments'),
        ('comment', '0003_auto_20211031_1826'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('user', 'book')},
        ),
    ]
